# .travis.yml
node_js:
- 8

script:
- npm install
- ./node_modules/.bin/docpress build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  target_branch: gh-pages
  on:
    branch: master
